### ISSUE TITLE
Perl 5.14.5 does not exist

### ISSUE THREAD

**Issue by eserte** [stevan/p5-Method-Traits#3]
The minimum perl prereq is 5.14.5, but this version does not exist. The latest in the 5.14.x series is 5.14.4. And the test suite actually passes with 5.14.4.

**Comment by stevan** [comment]
Thanks, fixed in git and will go out with the next release.

**Comment by tobyink** [comment]
The documentation says:
> Prior to Perl 5.15.4 [...]

And use that to justify requiring Perl 5.14.4.

But 5.15.4 != 5.14.4.

**Comment by stevan** [comment]
Fixed, will go out in the next release. Thanks for noticing it.
